name: Flutter-CI
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      # Flutter setup
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: "Enable web"
        run: "flutter config --enable-web"

      - name: "Setup chromedriver"
        uses: nanasess/setup-chromedriver@v1

      - name: Run integration tests
        run: |
          chromedriver --port=4444 --enable-chrome-logs --headless --url-base=/wd/hub &
          flutter drive --driver=test_driver/integration_test.dart --target=integration_test/example_test.dart -d chrome